---
title: "CovidOU_gen_3"
author: "Molly Cui"
date: "2023-07-11"
output: html_document
---

```{r}
#wider priors 1
rm(list=ls())
require(deSolve)
set.seed(2024)

#Simulate a bm process
ornstein_uhlenbeck <- function(n,theta,sigma,x0,lens,mu,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + theta*(mu[i-1]-x[i-1])*dt + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times=1:tims
e = rnorm(n = length(times) , sd = 1)
mu = vector(length=tims) 
  for (t in 1:tims) {
    if (t <= 120){
      mu[t]=-0.02      }                    #No lock-down policy
    else {mu[t]=-0.2-0.02 }                 #Lock-down policy
  }
  mu = ts(mu)
x = ornstein_uhlenbeck(tims, theta=0.05, sigma=sqrt(0.004), x0=0, tims,mu,e)

# Replication Generation function
gen_ode_model <- function(rep_time = 200, ori_seed = 20241, tims = 365, 
                          n = 52196381,ini_state = c(t=1,S=N-1, E=1, I=0, R=0),
                          tau = 0.1){
  
  times = 1:tims
  N = n
  
  #Construct matrix dataframe of states: times*replicates
  Zs = setNames(data.frame(matrix(NA, nrow = tims, ncol = rep_time)), paste0("Z", 1:rep_time))
  Ys = setNames(Zs, paste0("Y", 1:rep_time))
  dSs = setNames(Zs, paste0("dS", 1:rep_time))
  dEs = setNames(Zs, paste0("dE", 1:rep_time))
  dIs = setNames(Zs, paste0("dI", 1:rep_time))
  dRs = setNames(Zs, paste0("dR", 1:rep_time)) 
  
  # add params
  ks = setNames(Zs, paste0("k", 1:rep_time))
  gammas = setNames(Zs, paste0("gamma", 1:rep_time))
  
  # add x and e dataframe
  
  xs = setNames(Zs, paste0("x", 1:rep_time))
  es = setNames(Zs, paste0("e", 1:rep_time))
  
  
  # params = pars   ####
  initial_state = ini_state
  tau1 = tau
  
  #Main ODE Model
  Covid_OU <- function(time, current_state, params){
    
    with(as.list(c(current_state, params)),{
      
      # N <- S+E+I+R
      dt <- 1
      dS <- -exp(x[t])*S*(E+0.1*I)/N
      dE <- exp(x[t])*S*(E+0.1*I)/N - E*(1/k+1/gamma)
      dI <- E/k-I*(1/gamma+0.0087)
      dR <- (I+E)/gamma+0.0087*I
      
      return(list(c( dt, dS, dE, dI, dR)))
    })
  }
 
  ## Replicate 200 times-Monte Carlo trials for 200 
  for (rep_i in 1:rep_time) {
    set.seed(ori_seed + 1000*rep_i)
    
    k = rtruncnorm(1, a=0, b=Inf, mean = 5, sd = 1)
    gamma = rtruncnorm(1, a=0, b=Inf, mean = 9, sd = 1)
  
    params = c(k, gamma)
    
    model4 = ode(initial_state, times, Covid_OU, params)
    
    Z1 = model4[,4]/k
    
    Y1 = vector(length = tims)
    
    for (i in 1:tims){
      Y1[i] = rlnorm(1,log(Z1[i]/5),tau1)
    }
    
    dSi = model4[,3]
    dEi = model4[,4]
    dIi = model4[,5]
    dRi = model4[,6]
    
    ks[, rep_i] = k
    gammas[, rep_i] = gamma
    Zs[, rep_i] = Z1
    Ys[, rep_i] = Y1
    dSs[, rep_i] = dSi
    dEs[, rep_i] = dEi
    dIs[, rep_i] = dIi
    dRs[, rep_i] = dRi
  
    xs[, rep_i] = x
    es[, rep_i] = e
    
  }
  
  # output
  return(list(    
    Z = Zs,
    Y = Ys,
    dS = dSs,
    dE = dEs,
    dI = dIs,
    dR = dRs,
    k = ks,
    gamma = gammas,
    x = xs,
    e = es))
}
ode_example <- gen_ode_model(200)

## for param k
k_s = ncol(ode_example$k)
ks_mean = apply(ode_example$k,1,mean)
ks_95 = apply(ode_example$k, 1, quantile, probs=0.95)
ks_05 = apply(ode_example$k, 1, quantile, probs=0.05)
for (i in 1:k_s) {
  if (i == 1){
    plot(ode_example$k[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$k)),
         xlab = 'Times', ylab = 'param k',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$k[,i], col="cornsilk2")
    
  }
  lines(ks_mean,col="black",type="l")
  lines(ks_95,col="black",lty="dotdash")
  lines(ks_05,col="black",lty="dotdash")
}

## for param gamma
gamma_s = ncol(ode_example$gamma)
gammas_mean = apply(ode_example$gamma,1,mean)
gammas_95 = apply(ode_example$gamma, 1, quantile, probs=0.95)
gammas_05 = apply(ode_example$gamma, 1, quantile, probs=0.05)
for (i in 1:gamma_s) {
  if (i == 1){
    plot(ode_example$gamma[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$gamma)),
         xlab = 'Times', ylab = 'param gamma',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$gamma[,i], col="cornsilk2")
  }
  lines(gammas_mean,col="black",type="l")
  lines(gammas_95,col="black",lty="dotdash")
  lines(gammas_05,col="black",lty="dotdash")
}


## for z

zs = ncol(ode_example$Z)

for (i in 1:zs) {
  if (i == 1){
    plot(ode_example$Z[,1], col="darkblue", type = "l", 
         ylim = c(0, max(ode_example$Z)),
         xlab = 'Times', ylab = 'state Z',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$Z[,i], col="darkblue")
  }
}

## for y

ys = ncol(ode_example$Y)

for (i in 1:ys) {
  if (i == 1){
    plot(ode_example$Y[,1], col="darkred", type = "l", 
         ylim = c( min(ode_example$Y), max(ode_example$Y)),
         xlab = 'Times', ylab = 'incidence Y',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$Y[,i], col="darkred")
  }
}

## for s

ss = ncol(ode_example$dS)

for (i in 1:ss) {
  if (i == 1){
    plot(ode_example$dS[,1], col="skyblue", type = "l", 
         ylim = c(min(ode_example$dS), max(ode_example$dS)),
         xlab = 'Times', ylab = 'state S',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dS[,i], col="skyblue")
  }
}


## for e

es = ncol(ode_example$dE)

for (i in 1:es) {
  if (i == 1){
    plot(ode_example$dE[,1], col="yellow3", type = "l", 
         ylim = c(min(ode_example$dE), max(ode_example$dE)),
         xlab = 'Times', ylab = 'state E',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dE[,i], col="yellow3")
  }
}


## for i

is = ncol(ode_example$dI)

for (i in 1:is) {
  if (i == 1){
    plot(ode_example$dI[,1], col="pink3", type = "l", 
         ylim = c(min(ode_example$dI), max(ode_example$dI)),
         xlab = 'Times', ylab = 'state I',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dI[,i], col="pink3")
  }
}


## for R

rs = ncol(ode_example$dR)

for (i in 1:rs) {
  if (i == 1){
    plot(ode_example$dR[,1], col="darkgreen", type = "l", 
         ylim = c(min(ode_example$dR), max(ode_example$dR)),
         xlab = 'Times', ylab = 'state R',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dR[,i], col="darkgreen")
  }
}



############### add plot of x and e

## for x
xs = ncol(ode_example$x)

for (i in 1:xs) {
  if (i == 1){
    plot(ode_example$x[,1], col="orange2", type = "l", 
         ylim = c(min(ode_example$x), max(ode_example$x)),
         xlab = 'Times', ylab = 'Brownian Motion x',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$x[,i], col="orange2")
  }
}

## for beta
xs = ncol(ode_example$x)

for (i in 1:xs) {
  if (i == 1){
    plot(exp(ode_example$x[,1]), col="orange2", type = "l", 
         ylim = c(min(exp(ode_example$x)), max(exp(ode_example$x))),
         xlab = 'Times', ylab = expression(beta),main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(exp(ode_example$x[,i]), col="orange2")
  }
}

## for e

# es = ncol(ode_example$e)
# 
# for (i in 1:es) {
#   if (i == 1){
#     plot(ode_example$e[,1], col="grey", type = "l", 
#          ylim = c(min(ode_example$e), max(ode_example$e)),
#          xlab = 'Times', ylab = 'e',main="Covid_ou model Monte Carlo tirals")
#   }
#   else{
#     lines(ode_example$e[,i], col="grey")
#   }
# }
# 

## for all


lims = c(0, max(max(ode_example$dS), max(ode_example$dE), 
                max(ode_example$dI), max(ode_example$dR)))

ss = ncol(ode_example$dS)

for (i in 1:ss) {
  if (i == 1){
    plot(ode_example$dS[,1], col="skyblue", type = "l", 
         ylim = lims,
         xlab = 'Times', ylab = 'All states')
  }
  else{
    lines(ode_example$dS[,i], col="skyblue")
  }
  lines(ode_example$dE[,i], col="yellow3")
  lines(ode_example$dI[,i], col="pink3")
  lines(ode_example$dR[,i], col="darkgreen")
}
```


```{r}
#wider priors 1
rm(list=ls())
require(deSolve)
require(truncnorm)
set.seed(2024)

#Simulate a bm process
ornstein_uhlenbeck <- function(n,theta,sigma,x0,lens,mu,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + theta*(mu[i-1]-x[i-1])*dt + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times=1:tims
e = rnorm(n = length(times) , sd = 1)

#Make mu_x a function with varying a & b
mu_x <- function(n,b0,b1){
  mu = vector(length=n) 
 for (t in 1:n) {
    if (t <= 120){
      mu[t]=b0     }                    #No lock-down policy
    else {mu[t]=b0 + b1 }
 }
  return(mu)
}
# x = ornstein_uhlenbeck(tims, theta=0.05, sigma=sqrt(0.004), x0=0, tims,mu,e)

# Replication Generation function
gen_ode_model <- function(rep_time = 200, ori_seed = 20241, tims = 365, 
                          n = 52196381,ini_state = c(t=1,S=N-1, E=1, I=0, R=0),
                          tau = 0.1){
  
  times = 1:tims
  N = n
  
  #Construct matrix dataframe of states: times*replicates
  Zs = setNames(data.frame(matrix(NA, nrow = tims, ncol = rep_time)), paste0("Z", 1:rep_time))
  Ys = setNames(Zs, paste0("Y", 1:rep_time))
  dSs = setNames(Zs, paste0("dS", 1:rep_time))
  dEs = setNames(Zs, paste0("dE", 1:rep_time))
  dIs = setNames(Zs, paste0("dI", 1:rep_time))
  dRs = setNames(Zs, paste0("dR", 1:rep_time)) 
  
  # add params
  b0s = setNames(Zs, paste0("b0", 1:rep_time))
  b1s = setNames(Zs, paste0("b1", 1:rep_time))
  mus = setNames(Zs, paste0("mu", 1:rep_time))
  thetas = setNames(Zs, paste0("theta", 1:rep_time))
  sigmas = setNames(Zs, paste0("sigma", 1:rep_time))
  ks = setNames(Zs, paste0("k", 1:rep_time))
  gammas = setNames(Zs, paste0("gamma", 1:rep_time))
  
  # add x and e dataframe
  
  xs = setNames(Zs, paste0("x", 1:rep_time))
  es = setNames(Zs, paste0("e", 1:rep_time))
  
  
  # params = pars   ####
  initial_state = ini_state
  tau1 = tau
  
  #Main ODE Model
  Covid_OU <- function(time, current_state, params){
    
    with(as.list(c(current_state, params)),{
      
      # N <- S+E+I+R
      dt <- 1
      dS <- -exp(x[t])*S*(E+0.1*I)/N
      dE <- exp(x[t])*S*(E+0.1*I)/N - E*(1/k+1/gamma)
      dI <- E/k-I*(1/gamma+0.0087)
      dR <- (I+E)/gamma+0.0087*I
      
      return(list(c( dt, dS, dE, dI, dR)))
    })
  }
 
  ## Replicate 200 times-Monte Carlo trials for 200 
  for (rep_i in 1:rep_time) {
    set.seed(ori_seed + 1000*rep_i)
    
    b0 = rtruncnorm(1, a=-Inf, b=0, mean = -0.02, sd = 0.5) ##
    b1 = rtruncnorm(1, a=-Inf, b=0, mean = -0.2, sd = 0.5) ##
    mu = mu_x(tims,b0,b1)
    
    theta = rtruncnorm(1, a=0, b=1, mean = 0.05, sd = 0.1) ## 0.1
    sigma = rtruncnorm(1, a=0, b=1, mean = sqrt(0.004), sd = 0.1) ## 0.1
    x = ornstein_uhlenbeck(tims, theta, sigma, x0=0, tims,mu,e)
    
    k = rtruncnorm(1, a=0, b=Inf, mean = 5, sd = 1) ##
    # k = runif(1, min=2, max = 10)
    gamma = rtruncnorm(1, a=0, b=Inf, mean = 9, sd = 1) ##
    # gamma = runif(1,min=5, max = 14)
    params = c(k, gamma)
    
    model4 = ode(initial_state, times, Covid_OU, params)
    
    Z1 = model4[,4]/k
    
    Y1 = vector(length = tims)
    
    for (i in 1:tims){
      Y1[i] = rlnorm(1,log(Z1[i]/5),tau1)
    }
    
    dSi = model4[,3]
    dEi = model4[,4]
    dIi = model4[,5]
    dRi = model4[,6]
    
    b0s[, rep_i] = b0
    b1s[, rep_i] = b1
    mus[, rep_i] = mu
    thetas[, rep_i] = theta
    sigmas[, rep_i] = sigma
    ks[, rep_i] = k
    gammas[, rep_i] = gamma
    
    Zs[, rep_i] = Z1
    Ys[, rep_i] = Y1
    dSs[, rep_i] = dSi
    dEs[, rep_i] = dEi
    dIs[, rep_i] = dIi
    dRs[, rep_i] = dRi
  
    xs[, rep_i] = x
    es[, rep_i] = e
    
  }
  
  # output
  return(list(    
    Z = Zs,
    Y = Ys,
    dS = dSs,
    dE = dEs,
    dI = dIs,
    dR = dRs,
    b0 = b0s,
    b1 = b1s,
    mu = mus,
    theta = thetas,
    sigma = sigmas,
    k = ks,
    gamma = gammas,
    x = xs,
    e = es))
}
ode_example <- gen_ode_model(200)

## for param b0
b0_s = ncol(ode_example$b0)
b0s_mean = apply(ode_example$b0,1,mean)
b0s_95 = apply(ode_example$b0, 1, quantile, probs=0.95)
b0s_05 = apply(ode_example$b0, 1, quantile, probs=0.05)
for (i in 1:b0_s) {
  if (i == 1){
    plot(ode_example$b0[,1], col="cornsilk2", type = "l", 
         ylim = c(min(ode_example$b0), max(ode_example$b0)),
         xlab = 'Times', ylab = 'param b0',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$b0[,i], col="cornsilk2")
    
  }
  lines(b0s_mean,col="black",type="l")
  lines(b0s_95,col="black",lty="dotdash")
  lines(b0s_05,col="black",lty="dotdash")
}
## for param b1
b1_s = ncol(ode_example$b1)
b1s_mean = apply(ode_example$b1,1,mean)
b1s_95 = apply(ode_example$b1, 1, quantile, probs=0.95)
b1s_05 = apply(ode_example$b1, 1, quantile, probs=0.05)
for (i in 1:b1_s) {
  if (i == 1){
    plot(ode_example$b1[,1], col="cornsilk2", type = "l", 
         ylim = c(min(ode_example$b1), max(ode_example$b1)),
         xlab = 'Times', ylab = 'param b1',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$b1[,i], col="cornsilk2")
    
  }
  lines(b1s_mean,col="black",type="l")
  lines(b1s_95,col="black",lty="dotdash")
  lines(b1s_05,col="black",lty="dotdash")
}
## for param theta
theta_s = ncol(ode_example$theta)
thetas_mean = apply(ode_example$theta,1,mean)
thetas_95 = apply(ode_example$theta, 1, quantile, probs=0.95)
thetas_05 = apply(ode_example$theta, 1, quantile, probs=0.05)
for (i in 1:theta_s) {
  if (i == 1){
    plot(ode_example$theta[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$theta)),
         xlab = 'Times', ylab = 'param theta',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$theta[,i], col="cornsilk2")
    
  }
  lines(thetas_mean,col="black",type="l")
  lines(thetas_95,col="black",lty="dotdash")
  lines(thetas_05,col="black",lty="dotdash")
}
##for param sigma
sigma_s = ncol(ode_example$sigma)
sigmas_mean = apply(ode_example$sigma,1,mean)
sigmas_95 = apply(ode_example$sigma, 1, quantile, probs=0.95)
sigmas_05 = apply(ode_example$sigma, 1, quantile, probs=0.05)
for (i in 1:sigma_s) {
  if (i == 1){
    plot(ode_example$sigma[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$sigma)),
         xlab = 'Times', ylab = 'param sigma',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$sigma[,i], col="cornsilk2")
    
  }
  lines(sigmas_mean,col="black",type="l")
  lines(sigmas_95,col="black",lty="dotdash")
  lines(sigmas_05,col="black",lty="dotdash")
}
## for param k
k_s = ncol(ode_example$k)
ks_mean = apply(ode_example$k,1,mean)
ks_95 = apply(ode_example$k, 1, quantile, probs=0.95)
ks_05 = apply(ode_example$k, 1, quantile, probs=0.05)
for (i in 1:k_s) {
  if (i == 1){
    plot(ode_example$k[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$k)),
         xlab = 'Times', ylab = 'param k',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$k[,i], col="cornsilk2")
    
  }
  lines(ks_mean,col="black",type="l")
  lines(ks_95,col="black",lty="dotdash")
  lines(ks_05,col="black",lty="dotdash")
}

## for param gamma
gamma_s = ncol(ode_example$gamma)
gammas_mean = apply(ode_example$gamma,1,mean)
gammas_95 = apply(ode_example$gamma, 1, quantile, probs=0.95)
gammas_05 = apply(ode_example$gamma, 1, quantile, probs=0.05)
for (i in 1:gamma_s) {
  if (i == 1){
    plot(ode_example$gamma[,1], col="cornsilk2", type = "l", 
         ylim = c(0, max(ode_example$gamma)),
         xlab = 'Times', ylab = 'param gamma',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$gamma[,i], col="cornsilk2")
  }
  lines(gammas_mean,col="black",type="l")
  lines(gammas_95,col="black",lty="dotdash")
  lines(gammas_05,col="black",lty="dotdash")
}


## for z

zs = ncol(ode_example$Z)

for (i in 1:zs) {
  if (i == 1){
    plot(ode_example$Z[,1], col="darkblue", type = "l", 
         ylim = c(0, max(ode_example$Z)),
         xlab = 'Times', ylab = 'state Z',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$Z[,i], col="darkblue")
  }
}

## for y

ys = ncol(ode_example$Y)

for (i in 1:ys) {
  if (i == 1){
    plot(ode_example$Y[,1], col="darkred", type = "l", 
         ylim = c( min(ode_example$Y), max(ode_example$Y)),
         xlab = 'Times', ylab = 'incidence Y',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$Y[,i], col="darkred")
  }
}

## for s

ss = ncol(ode_example$dS)

for (i in 1:ss) {
  if (i == 1){
    plot(ode_example$dS[,1], col="skyblue", type = "l", 
         ylim = c(min(ode_example$dS), max(ode_example$dS)),
         xlab = 'Times', ylab = 'state S',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dS[,i], col="skyblue")
  }
}


## for e

es = ncol(ode_example$dE)

for (i in 1:es) {
  if (i == 1){
    plot(ode_example$dE[,1], col="yellow3", type = "l", 
         ylim = c(min(ode_example$dE), max(ode_example$dE)),
         xlab = 'Times', ylab = 'state E',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dE[,i], col="yellow3")
  }
}


## for i

is = ncol(ode_example$dI)

for (i in 1:is) {
  if (i == 1){
    plot(ode_example$dI[,1], col="pink3", type = "l", 
         ylim = c(min(ode_example$dI), max(ode_example$dI)),
         xlab = 'Times', ylab = 'state I',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dI[,i], col="pink3")
  }
}


## for R

rs = ncol(ode_example$dR)

for (i in 1:rs) {
  if (i == 1){
    plot(ode_example$dR[,1], col="darkgreen", type = "l", 
         ylim = c(min(ode_example$dR), max(ode_example$dR)),
         xlab = 'Times', ylab = 'state R',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$dR[,i], col="darkgreen")
  }
}



############### add plot of x and e
## for mu
mus = ncol(ode_example$mu)

for (i in 1:mus) {
  if (i == 1){
    plot(ode_example$mu[,1], col="brown3", type = "l", 
         ylim = c(min(ode_example$mu), max(ode_example$mu)),
        xlab = 'Times', ylab = 'Brownian Motion mu',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$mu[,i], col="brown3")
  }
}
## for x
xs = ncol(ode_example$x)

for (i in 1:xs) {
  if (i == 1){
    plot(ode_example$x[,1], col="orange2", type = "l", 
         ylim = c(min(ode_example$x), max(ode_example$x)),
         xlab = 'Times', ylab = 'Brownian Motion x',main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(ode_example$x[,i], col="orange2")
  }
}

## for beta
xs = ncol(ode_example$x)

for (i in 1:xs) {
  if (i == 1){
    plot(exp(ode_example$x[,1]), col="orange2", type = "l", 
         ylim = c(min(exp(ode_example$x)), max(exp(ode_example$x))),
         xlab = 'Times', ylab = expression(beta),main="H1N1BM model Monte Carlo tirals")
  }
  else{
    lines(exp(ode_example$x[,i]), col="orange2")
  }
}

## for e

# es = ncol(ode_example$e)
# 
# for (i in 1:es) {
#   if (i == 1){
#     plot(ode_example$e[,1], col="grey", type = "l", 
#          ylim = c(min(ode_example$e), max(ode_example$e)),
#          xlab = 'Times', ylab = 'e',main="Covid_ou model Monte Carlo tirals")
#   }
#   else{
#     lines(ode_example$e[,i], col="grey")
#   }
# }
# 

## for all


lims = c(0, max(max(ode_example$dS), max(ode_example$dE), 
                max(ode_example$dI), max(ode_example$dR)))

ss = ncol(ode_example$dS)

for (i in 1:ss) {
  if (i == 1){
    plot(ode_example$dS[,1], col="skyblue", type = "l", 
         ylim = lims,
         xlab = 'Times', ylab = 'All states')
  }
  else{
    lines(ode_example$dS[,i], col="skyblue")
  }
  lines(ode_example$dE[,i], col="yellow3")
  lines(ode_example$dI[,i], col="pink3")
  lines(ode_example$dR[,i], col="darkgreen")
}
```