---
title: "H1N1_BM Model Data Generation"
author: "Molly Cui"
date: "2023-06-26"
output: html_document
---


```{r}
#Use log_normal obs dis-method 1
rm(list=ls())
require(deSolve)
set.seed(5204) 
times <- 1:365
sigma=0.07
## first, simulate a set of random deviates
# e <- rnorm(n = length(times) , sd = 1)
e <- rnorm(n = length(times) ,mean=0, sd = 1)
plot(e,type='l')
ornstein_uhlenbeck <- function(n,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + e[i-1]}
  }
  
  return(x)
}
tims=365
times = 1:tims
x = ornstein_uhlenbeck(tims, x0=0, tims,e)
# write.csv(e,"simulateh1n1x2.csv")
beta<- exp(sigma*x)
# plot(beta,type='l')
plot(beta,type='p',ylab="Transmission rate beta",xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
# write.csv(beta,"simulateh1n1beta2.csv")
```
```{r}
#Use log_normal obs dis-method 2: correct
rm(list=ls())
require(deSolve)
set.seed(5204)
## first, simulate a set of random deviates
tims=365
times = 1:tims
# e <- rnorm(n = length(times) ,mean=0, sd = 1)
# plot(e,type='l')
ornstein_uhlenbeck <- function(n,sigma,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + sigma*e[i-1]}
  }
  
  return(x)
}
# e = rnorm(n = length(times) , sd = 1)
# x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)
e<-replicate(n=50, ornstein_uhlenbeck(tims, sigma=0.1,x0=0, tims,rnorm(n = length(times) , sd = 1)))
# tim<-replicate(n=50,times)
es = ncol(e)
e_mean = apply(e,1,mean)
for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col=rainbow(1)[1], type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Times', ylab = expression(B(t)),main="Brownian Motion 50 simulated paths")
  }
  else{
    lines(e[,i], col=rainbow(90)[i])
  }
  lines(e_mean,col='black')
}

# beta<- exp(x)
# 
# plot(beta,type='p',ylab="Transmission rate beta",xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
# lines(beta,col="darkblue")

```

```{r}
#Use log_normal obs dis-method 2: general case-web check 1
rm(list=ls())
set.seed(531)
## first, simulate a set of random deviates: Time=1, n=lens=100 partitions, delta t=1/100
tims=1
times<-seq(0.01,1,1/100)
e <- rnorm(n = 100 ,mean=0, sd = sqrt(1/100))
plot(e,type='l')
ornstein_uhlenbeck <- function(T,n,x0,lens,e){
  dt <- T/n
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + e[i-1]}
  }
  
  return(x)
}

# e = rnorm(n = length(times) , sd = 1)
# x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)
e<-replicate(n=10, ornstein_uhlenbeck(T=1,n=100, x0=0, 100,rnorm(n = 100 , sd = sqrt(1/100))))
tim<-replicate(n=10,times)
es = ncol(e)

for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col="darkseagreen", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion Monte Carlo tirals")
  }
  else{
    lines(e[,i], col="darkseagreen")
  }
}
```


```{r}
#Use log_normal obs dis-method 2: general case-web check 2
rm(list=ls())
set.seed(531)
## first, simulate a set of random deviates: Time=10, n=lens=100 partitions, delta t=10/100
tims=10
times<-seq(0.1,10,10/100) 

e <- rnorm(n = 100 ,mean=0, sd = sqrt(10/100))
plot(e,type='l')
ornstein_uhlenbeck <- function(T,n,x0,lens,e){
  dt <- T/n
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + e[i-1]}
  }
  
  return(x)
}

# e = rnorm(n = length(times) , sd = 1)
# x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)
e<-replicate(n=50, ornstein_uhlenbeck(T=10,n=100, x0=0, 100,rnorm(n = 100 , sd = sqrt(10/100))))
tim<-replicate(n=50,times)
es = ncol(e)

for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col="darkseagreen", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion Monte Carlo tirals")
  }
  else{
    lines(e[,i], col="darkseagreen")
  }
}
for (i in 1:es) {
  if (i == 1){
    plot(e[,1]/tim[,1], col="cornflowerblue", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)/t),main="Brownian Motion long-time behaviour ")
  }
  else{
    lines(e[,i]/tim[,i], col="cornflowerblue")
  }
}
```

```{r}
#Use log_normal obs dis-method 2: general case-web check 3
rm(list=ls())
set.seed(531)
## first, simulate a set of random deviates: Time=500, n=lens=5000 partitions, delta t=500/5000
tims=500
times<-seq(0.1,500,500/5000)

e <- rnorm(n = 5000 ,mean=0, sd = sqrt(500/5000))
plot(e,type='l')
ornstein_uhlenbeck <- function(T,n,x0,lens,e){
  dt <- T/n
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + e[i-1]}
  }
  
  return(x)
}

# e = rnorm(n = length(times) , sd = 1)
# x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)
e<-replicate(n=100, ornstein_uhlenbeck(T=500,n=5000, x0=0, lens=5000,e=rnorm(n = 5000 , sd = sqrt(500/5000))))
tim<-replicate(n=100,times)
es = ncol(e)
e_mean = apply(e,1,mean)
for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col=rainbow(1)[1], type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion 100 simulated paths")
  }
  else{
    lines(e[,i], col=rainbow(90)[i])
  }
   lines(e_mean,col='black')
}
for (i in 1:es) {
  if (i == 1){
    plot(e[,1]/tim[,1], col="cornflowerblue", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)/t),main="Brownian Motion long-time behaviour ")
  }
  else{
    lines(e[,i]/tim[,i], col="cornflowerblue")
  }
}
```




```{r}
#Use log_normal obs dis-method 3: cumsum questionable
set.seed(5204)
rm(list=ls())
require(deSolve)
times <- 1:365
sigma <- 0.07
# first, simulate a set of random deviates
e <- rnorm(n = length(times) , sd = 1)
# # now compute their cumulative sum
# e <- c(0, cumsum(e))
e <- cumsum(e)
plot(e,type='l')
beta<- exp(sigma*e)
plot(beta,type='p',ylab="Transmission rate beta",xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
```
```{r}
#Use log_normal obs dis-method 3: general case-web check 1
rm(list=ls())
# set.seed(531)
## first, simulate a set of random deviates: Time=1, n=lens=100 partitions, delta t=1/100
tims=1
times<-seq(0.01,1,1/100)
e <- rnorm(n = 100 ,mean=0, sd = sqrt(1/100))
plot(e,type='l')

e<-replicate(n=10,cumsum(rnorm(n = 100 , sd = sqrt(1/100))))
tim<-replicate(n=10,times)
es = ncol(e)

for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col="darkseagreen", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion Monte Carlo tirals")
  }
  else{
    lines(e[,i], col="darkseagreen")
  }
}
```
```{r}
#Use log_normal obs dis-method 3: general case-web check 2
rm(list=ls())
set.seed(531)
## first, simulate a set of random deviates: Time=10, n=lens=100 partitions, delta t=10/100
tims=10
times<-seq(0.1,10,10/100) 

e <- rnorm(n = 100 ,mean=0, sd = sqrt(10/100))
plot(e,type='l')
e<-replicate(n=50,cumsum(rnorm(n = 100 , sd = sqrt(10/100))))
tim<-replicate(n=50,times)
es = ncol(e)

for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col="darkseagreen", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion Monte Carlo tirals")
  }
  else{
    lines(e[,i], col="darkseagreen")
  }
}
for (i in 1:es) {
  if (i == 1){
    plot(e[,1]/tim[,1], col="cornflowerblue", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)/t),main="Brownian Motion long-time behaviour ")
  }
  else{
    lines(e[,i]/tim[,i], col="cornflowerblue")
  }
}
```
```{r}
#Use log_normal obs dis-method 3: general case-web check 3
rm(list=ls())
# set.seed(531)
## first, simulate a set of random deviates: Time=500, n=lens=5000 partitions, delta t=500/5000
tims=500
times<-seq(0.1,500,500/5000)

e <- rnorm(n = 5000 ,mean=0, sd = sqrt(500/5000))
plot(e,type='l')

e<-replicate(n=5000,cumsum(rnorm(n = 5000 , sd = sqrt(500/5000))))
tim<-replicate(n=5000,times)
es = ncol(e)

for (i in 1:es) {
  if (i == 1){
    plot(e[,1], col="darkseagreen", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)),main="Brownian Motion Monte Carlo tirals")
  }
  else{
    lines(e[,i], col="darkseagreen")
  }
}
for (i in 1:es) {
  if (i == 1){
    plot(e[,1]/tim[,1], col="cornflowerblue", type = "l",
         ylim = c(min(e), max(e)),
         xlab = 'Time points', ylab = expression(B(t)/t),main="Brownian Motion long-time behaviour ")
  }
  else{
    lines(e[,i]/tim[,i], col="cornflowerblue")
  }
}
```


```{r}
#Use log_normal obs dis-using method 2
rm(list=ls())
require(deSolve)
set.seed(5227) #5220 5222 5224 5226
times <- 1:365
N=52196381
## first, simulate a set of random deviates
e <- rnorm(n = length(times) ,mean=0, sd = 1)
plot(e,type='l')
ornstein_uhlenbeck <- function(n,sigma,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times = 1:tims
x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)

beta<- exp(x)

# plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
plot(beta,type='p',ylab="Transmission rate beta",xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
write.csv(beta,"h1n1bmdg_beta1.csv")
#Put the function to the top db checking the text of beta
H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    # N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=2, gamma=5, beta=beta)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-model1[,4]/2 #############

tau1 <- 0.1#runif(1,0,1)
Y1 <-vector(length = 365)
for (i in 1:365){
  Y1[i]<- rlnorm(1,log(Z1[i]/5),tau1)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
write.csv(Y1,"h1n1bmdg_y1.csv")
write.csv(model1,"h1n1bmdg_model1.csv")

```
```{r}
#Use log_normal obs dis-using method 3
rm(list=ls())
require(deSolve)
set.seed(5227) #5204 5205 5207 5209 5210 5213
times <- 1:365
N=52196381
## first, simulate a set of random deviates
e <- rnorm(n = length(times) , sd = 1)
plot(e,type='l')
x <- cumsum(e)

sigma = 0.07
beta<- exp(sigma*x)

plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
write.csv(beta,"h1n1bmdg_beta2.csv")
H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    # N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=2, gamma=5, beta=beta)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-model1[,4]/2

tau1 <- 0.1#runif(1,0,1)
Y1 <-vector(length = 365)
for (i in 1:365){
  #Y1[i]<- rlnorm(1,log(Z1[i,]/5),tau1)
  Y1[i]<- rlnorm(1,log(Z1[i]/5),tau1)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
write.csv(Y1,"h1n1bmdg_y2.csv")
write.csv(model1,"h1n1bmdg_model2.csv")

```


```{r}
#Use Poisson obs dis
rm(list=ls())
require(deSolve)
set.seed(5227) #5204 5205 5207 5209 5210 5213
times <- 1:365
N=52196381
## first, simulate a set of random deviates
e <- rnorm(n = length(times) ,mean=0, sd = 1)
plot(e,type='l')
ornstein_uhlenbeck <- function(n,sigma,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times = 1:tims
x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)

beta<- exp(x)

plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
write.csv(beta,"h1n1bmdg_beta3.csv")
H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=2, gamma=5,beta=beta)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-model1[,4]/2

Y1 <-vector(length = 365)
for (i in 1:365){
  Y1[i]<- rpois(1,Z1[i]/5)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
write.csv(Y1,"h1n1bmdg_y3.csv")
write.csv(model1,"h1n1bmdg_model3.csv")
```

```{r}
#Use Poisson obs dis-using method 3
rm(list=ls())
require(deSolve)
set.seed(5216) #5204 5205 5207 5209 5210 5213
times <- 1:365
N=52196381
## first, simulate a set of random deviates
e <- rnorm(n = length(times) , sd = 1)
plot(e,type='l')
x <- cumsum(e)

sigma = 0.07
beta<- exp(sigma*x)

plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
write.csv(beta,"h1n1bmdg_beta4.csv")
H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    # N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=2, gamma=5, beta=beta)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-model1[,4]/2

Y1 <-vector(length = 365)
for (i in 1:365){
  #Y1[i]<- rlnorm(1,log(Z1[i,]/5),tau1)
  Y1[i]<- rpois(1,Z1[i]/5)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
write.csv(Y1,"h1n1bmdg_y4.csv")
write.csv(model1,"h1n1bmdg_model4.csv")

```
```{r}
#Use log_normal obs dis-using method 2
rm(list=ls())
require(deSolve)
set.seed(5216) #5204 5205 5207 5209 5210 5213
times <- 1:365
N=52196381
## first, simulate a set of random deviates
e <- rnorm(n = length(times) ,mean=0, sd = 1)
plot(e,type='l')
ornstein_uhlenbeck <- function(n,sigma,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times = 1:tims
e = rnorm(n = length(times) , sd = 1)
x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)

beta<- exp(x)

plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")
write.csv(beta,"h1n1bmdg_beta5.csv")
H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    # N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=1.59, gamma=1.08, beta=beta)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-model1[,4]/1.59 #############

tau1 <- 0.1#runif(1,0,1)
Y1 <-vector(length = 365)
for (i in 1:365){
  Y1[i]<- rlnorm(1,log(Z1[i]/5),tau1)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
write.csv(Y1,"h1n1bmdg_y5.csv")
write.csv(model1,"h1n1bmdg_model5.csv")

```


```{r}
#Use Binomial obs dis
rm(list=ls())
require(deSolve)
set.seed(5227) #5204 5205 5207 5209 5210 5213
times <- 1:365
N=52196381
## first, simulate a set of random deviates
# e <- rnorm(n = length(times) , sd = 1)
e <- rnorm(n = length(times) ,mean=0, sd = 1)
plot(e,type='l')
ornstein_uhlenbeck <- function(n,sigma,x0,lens,e){
  dt <- 1
  x<-vector(length=lens)
  for (i in 1:n) {
    if (i==1){x[i]=x0}
    else{
      x[i]  <-  x[i-1] + sigma*e[i-1]}
  }
  
  return(x)
}
tims=365
times = 1:tims
x = ornstein_uhlenbeck(tims, sigma=0.07,x0=0, tims,e)

beta<- exp(x)

plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="H1N1_BM model generated transmission rate")
lines(beta,col="darkblue")

H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


# params <- c(k=1.59, gamma=1.08)
params <- c(k=2, gamma=5)       ####parameter tunning step
library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

matplot(model1, type="l", lty=1, main="Generated H1N1_BM Model Trajectories", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

Z1 <-floor(model1[,4]/2)

Y1 <-vector(length = 365)
for (i in 1:365){
  #Y1[i]<- rlnorm(1,log(Z1[i,]/5),tau1)
  Y1[i]<- rbinom(1,Z1[i],1/5)
}
plot(Y1,type='p',ylab="Daily incidence Y",xlab="time",col="darkred",main="H1N1_BM model generated observation")
lines(Y1,col="darkblue")
```

```{r}
rm(list=ls())
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(pander)
library(lubridate)
library(latex2exp)
library(rbi)
library(rbi.helpers)

ncores <- 8
minParticles <- max(ncores, 16)
model_str <- "
model h1n1bm {
  obs y
  
  state S
  state E
  state I
  state R
  state x
  
  const k = 5
  const gamma = 9
  const sigma = sqrt(0.004)
  const theta = 0.05
  const a = -0.02
  const b = -0.2
  const tau = 0.1

  sub initial {
    S <- N-1
    E <- 1
    I <- 0
    R <- 0
    x ~ gaussian(-0.02, 0.2)
  }

  sub transition(delta = 1) {
    noise e
    e ~ wiener()
    mu <- a+b*Forcing
    ode{
      dx/dt = theta*(mu-x)+sigma*e
      dS/dt = -exp(x)*S*(0.1*I+E)/N
      dE/dt = exp(x)*S*(0.1*I+E)/N - E*(1/k+1/gamma)
      dI/dt = E/k-I*(1/gamma+0.0087)
      dR/dt = (I+E)/gamma+0.0087*I
    }
  }

  sub observation {
    y ~ log_normal(log(max((E/k)/5, 0)), tau)
  }

}"
covid <- bi_model(lines = stringi::stri_split_lines(model_str)[[1]])

T <- 365
nObs <- 365
input_lst <- list(N = 52196381,Forcing=Forcing)
synthetic_dataset <- generate_dataset(model=covid, end_time=T,
                                         noutputs = nObs, input=input_lst, seed="92")
synthetic_data <- bi_read(synthetic_dataset)

synthetic_df <- as.data.frame(synthetic_data)


write.csv(synthetic_df$y.value,"covidoudg2_Y121.csv")
write.csv(synthetic_df$x.value,"covidoudg2_x121.csv")
write.csv(exp(synthetic_df$x.value),"covidoudg2_beta121.csv")
write.csv(synthetic_df,"covidoudg2_model121.csv")

ggplot(synthetic_df, aes(y.time)) +
  geom_path(aes(y = y.value, colour="y.value")) +
  theme(legend.position="bottom") +
  ggtitle("Covid_OU model generated observation with Lognormal distribution") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Time") +
  ylab("Daily incidence Y")

ggplot(synthetic_df, aes(y.time)) +
  geom_path(aes(y = S.value, colour="S.value")) +
  geom_path(aes(y = E.value, colour="E.value")) +
  geom_path(aes(y = I.value, colour="I.value")) +
  geom_path(aes(y = R.value, colour="R.value")) +
  theme(legend.position="bottom") +
  ggtitle("Generated COVID_OU Model Trajectories") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Time") +
  ylab("Counts")

x <- read.csv("covidoudg2_x121.csv", header=TRUE, stringsAsFactors=FALSE)
plot(x,type='p',ylab=TeX(r"(OU process $X_{t}$)"),xlab="Time",col="darkred",main=TeX(r"(Generated OU process: $\theta=0.05$, $sigma=sqrt(0.004)$, $x_{0} \sim N(-0.02,0.2)$)"))
  lines(x,col="darkblue")
  abline(v=31, col="red")
axis(1, at=31,labels=31, col.axis="red", las=2)

beta <- read.csv("covidoudg2_beta121.csv", header=TRUE, stringsAsFactors=FALSE)
plot(beta,type='p',ylab=TeX(r"(Transmission rate $\beta$)"),xlab="time",col="darkred",main="COVIDOU model generated transmission rate")
lines(beta,col="darkblue")
abline(v=31, col="red")
axis(1, at=31,labels=31, col.axis="red", las=2)
tt1 <-expression('lockdown policy start')
text(80,0.6,tt1,col="red")
```
