---
title: "newcode_svm"
author: "Molly Cui"
date: "2023-11-27"
output: html_document
---
###Generate data: y_t-returns and alpha_t-volatility

```{r}
rm(list=ls())
T<-2000
beta <- 0.6
Phi <- 0.975
cQ <- sqrt(0.02) 
set.seed(9999)
num=Time=T
x=arima.sim(n=num+1,list(ar=0.975),sd=sqrt(0.02))
y=ts(beta*exp(x[-1]/2)*rnorm(num,0,sqrt(1)))  
write.csv(x,"svm_x2.csv")
write.csv(y,"svm_y2.csv")

par(mfrow=c(2,1));
plot(y, type = "l", main = "Simulated log-return process",
     xlab="Time",col = "black")
plot(x[-1], type = "l", main = "Hidden stochastic volatility process",
     xlab="Time",col = "blue")

```
###libbi code for inference
```{r}
rm(list=ls())
set.seed(0000889977)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(pander)
library(lubridate)
library(latex2exp)
library(rbi)
library(rbi.helpers)
ncores <- 12
# Load the data
v <- read.csv("svm_y2r.csv", header=FALSE, stringsAsFactors=FALSE) 
y <- data.frame(value = v) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, V1)
colnames(y) <- c("time","value")
model_str <- "
model StochasticVolatility {

  obs y
  
  state alpha
  
  noise epsilon
  
  param beta
  param phi
  param sigma_eta
  
  sub parameter {
    beta ~ truncated_gaussian(0.8, 0.1, lower = 0)
    phi ~ truncated_gaussian(0.45, 1, lower = -1, upper=1)
    sigma_eta ~ truncated_gaussian(sqrt(0.04), 0.1, lower=0)
  }
  
  sub proposal_parameter {
    beta ~ truncated_gaussian(beta, 0.1, lower = 0) 
    phi ~ truncated_gaussian(phi, 0.01, lower = -1, upper=1) 
    sigma_eta ~ truncated_gaussian(sigma_eta, 0.001)
  }
  
  sub initial {
    /* stationary distribution for alpha */
    alpha ~ normal(0.0, sqrt(sigma_eta**2/(1.0 - phi**2)));
  }

  sub transition {
    epsilon ~ normal(0,1);
    alpha <- phi*alpha + sigma_eta*epsilon;
  }

  sub observation {
    y ~ normal(0, beta*exp(0.5*alpha));
  }
}"
model <- bi_model(lines = stringi::stri_split_lines(model_str)[[1]])
end_time <- max(y$time)
obs_lst <- list(y = y %>% dplyr::filter(time <= end_time))
init_list <- list(beta=0.6,phi=0.975,sigma_eta=sqrt(0.02))
#LibBi wrapper 
#run launches LibBi with a particular set of command line arguments
bi_model <- libbi(model,end_time = end_time, 
                  init=init_list, obs = obs_lst)
#RBi.helpers adapt_particle
particles_adapted <- bi_model %>%
  sample(nsamples = 2000, nparticles = 16, 
         nthreads = ncores, proposal = 'prior') %>%
  adapt_particles(min = 16, max = 16*500)

#RBi.helpers adapt_proposal
proposal_adapted <- particles_adapted %>%
  sample(target = "posterior", nsamples = 2000, 
         nthreads = ncores, proposal = 'model') %>%
  adapt_proposal(min = 0.1, max = 0.4)

#Running pMCMC with burn-in
bi <- proposal_adapted %>%
  sample(nsamples = 2000, thin = 1, init=init_list)
bi_lst <- bi_read(bi %>% sample_obs)

write.csv(bi_lst,"svm_model2.csv")
fitY <- bi_lst$y %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(y %>% rename(Y = value))
write.csv(fitY,"svminf_y2.csv")
fitY <- read.csv("svminf_y2.csv", header=TRUE, stringsAsFactors=FALSE)
g1 <- ggplot(data = fitY) +
  geom_ribbon(aes(x = time, ymin = q25, ymax = q75), alpha = 0.3) +
  geom_ribbon(aes(x = time, ymin = q025, ymax = q975), alpha = 0.3) +
  geom_line(aes(x = time, y = value)) +
  geom_line(aes(x = time, y = Y), colour = "Red") +
  ylab("Daily return Y") +
  xlab("Time-Day")

w <- read.csv("svm_x2r.csv", header=FALSE, stringsAsFactors=FALSE) 
alpha <- data.frame(value = w) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, V1)
colnames(alpha) <- c("time","value")
fitalpha <- bi_lst$alpha %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(alpha %>% rename(Alpha = value))
write.csv(fitalpha,"svminf_x2.csv")
fitalpha <- read.csv("svminf_x2.csv", header=TRUE, stringsAsFactors=FALSE)
g2 <- ggplot(data = fitalpha) +
  geom_ribbon(aes(x = time, ymin = q25, ymax = q75), alpha = 0.3) +
  geom_ribbon(aes(x = time, ymin = q025, ymax = q975), alpha = 0.3) +
  geom_line(aes(x = time, y = q50)) +
  geom_point(aes(x = time, y = Alpha), colour = "Red") +
  ylab("Volatilities alpha") +
  xlab("Time-Day")

write.csv(bi_lst$beta$value,"svminf_beta2.csv")
write.csv(bi_lst$phi$value,"svminf_phi2.csv")
write.csv(bi_lst$sigma_eta$value,"svminf_sigma2.csv")
sigma<-read.csv("svminf_sigma2.csv", header=TRUE, stringsAsFactors=FALSE)
phi<-read.csv("svminf_phi2.csv", header=TRUE, stringsAsFactors=FALSE)
beta<-read.csv("svminf_beta2.csv", header=TRUE, stringsAsFactors=FALSE)
par(mfrow=c(3,1))
plot(sigma,type='l',main=TeX("Trace plot of ($\\sigma$)"),xlab="PMCMC iterations after first 5000 burn-in and following 10000 thinning by 5",ylab="sigma")
abline(h=sqrt(0.04), col="red")
abline(h=mean(sigma[,2]),col="blue")
plot(phi,type='l',main=TeX("Trace plot of ($\\phi$)"),xlab="PMCMC iterations after first 5000 burn-in and following 10000 thinning by 5",ylab="phi")
abline(h=0.975, col="red")
abline(h=mean(phi[,2]),col="blue")
plot(beta,type='l',main=TeX("Trace plot of ($\\beta$)"),xlab="PMCMC iterations after first 5000 burn-in and following 10000 thinning by 5",ylab="beta")
abline(h=0.6, col="red")
abline(h=mean(beta[,2]),col="blue")
```

