---
title: "Script automation"
author: "Molly Cui"
date: "2023-07-03"
output: html_document
---

```{r}
#############################################data generation example for h1n1-bm model#######################
rm(list=ls())
require(deSolve)
set.seed(00033) #other good options: #00033 #00036 #00043 #00048
times <- 1:365
N=52196381
sigma <- 0.07
## first, simulate a set of random deviates
e <- rnorm(n = length(times) - 1, sd = sqrt(0.01))
## now compute their cumulative sum
e <- c(0, cumsum(e))

write.csv(e,"simulateh1n1x1.csv")
beta<- exp({{ dxdt }})
plot(beta,type='l')
write.csv(beta,"simulateh1n1beta1.csv")

H1N1 <- function(time, current_state, params){
  
  with(as.list(c(current_state, params)),{
    
    N <- S+E+I+R
    dt <- 1
    dS <- -beta[t]*S*I/N
    dE <- beta[t]*S*I/N - E/k
    dI <- E/k - I/gamma
    dR <- I/gamma
    
    return(list(c(dt, dS, dE, dI, dR)))
  })
}


params <- c(k=1.59, gamma=1.08)

library('truncnorm')
R0 <- rtruncnorm(1, a=0, b=1, mean = 0.15, sd = 0.15)
E0 <-runif(1,-16, -9)
I0 <-runif(1,-16, -9)
#x <-runif(1, -5,2)
S <- N
R <- R0*S
S <- S - R

E <- exp(E0 + log(S))
S <- S - E
I <- exp(I0 + log(S))
S <- S - I


initial_state<- c(t=1, S=S, E=E, I=I, R=R)
#initial_state <- c(t=1,S=52196380, E=1, I=0, R=0)
model1 <- ode(initial_state, times, H1N1, params)

summary(model1)

#Simulation model plot
matplot(model1, type="l", lty=1, main="H1N1-BM SEIR model", xlab="Time",ylab = "Counts")
legend <- colnames(model1)[3:6]
legend("right", legend=legend, col=3:6, lty = 1)

#Generate observations based on the ode solutions
Z1 <-model1[,4]/1.59

tau1 <- 0.1
Y1 <-vector(length = 365)
for (i in 1:365){
  Y1[i]<- rlnorm(1,log(Z1[i]/5),tau1)
}

#Plot and save final observation input data for later simulation experiments
plot(Y1,type='l',ylab="Y obs", xlab = "Time")

write.csv(Y1,"simh1n1Y1.csv")
write.csv(model1,"simulateh1n1states1.csv")

```


```{r}
#para_template
rm(list=ls())
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(pander)
library(lubridate)
library(latex2exp)
library(rbi)
library(rbi.helpers)
# Load the data
v <- read.csv("covidbm_wk1.csv", header=FALSE, stringsAsFactors=FALSE) %>%
  rowSums()

y <- data.frame(value = v) %>%
  mutate(time = seq(7, by = 7, length.out = n())) %>%
  dplyr::select(time, value)

ncores <- 8
minParticles <- max(ncores, 16)
model_str <- "
model covidbm {
  obs y

  state S
  state E
  state I
  state R
  state x
  state Z

  input N
  
  param k
  param gamma
  param sigma
  param tau
  
  sub parameter {
    k ~ {{ param_k }}
    gamma ~ truncated_gaussian(5, 0.01, lower = 0) // gamma is the period, not the rate
    sigma ~ truncated_gaussian(sqrt(0.004), 0.001, lower = 0)
    tau ~ uniform(0, 1)
  }

  sub initial {
    S <- N-1
    E <- 1
    I <- 0
    R <- 0
    Z <- {{ initial_z }}
  }

  sub transition(delta = 1) {
  Z <- ((t_now) % 7 == 0 ? 0 : Z)
    noise e
    e ~ wiener()
    ode(alg = 'RK4(3)', h = 1.0, atoler = 1.0e-3, rtoler = 1.0e-8) {
      dx/dt = {{ dxdt }}
      dS/dt = -exp(x)*S*(0.1*I+E)/N
      dE/dt = exp(x)*S*(0.1*I+E)/N - E*(1/k+1/gamma)
      dI/dt = E/k-I*(1/gamma+0.0087)
      dR/dt = (I+E)/gamma+0.0087*I
      dZ/dt = E/k
    }
  }

  sub observation {
    y ~ log_normal(log(max(Z/5, 0)), tau)
  }
  
  sub proposal_parameter {
    k ~ truncated_gaussian(k, 0.001, lower = 0) 
    gamma ~ truncated_gaussian(gamma, 0.001, lower = 0) 
    sigma ~ truncated_gaussian(sigma, 0.001, lower = 0)
    tau ~ gaussian(tau, 0.05)
  }
}"
model <- bi_model(lines = stringi::stri_split_lines(model_str)[[1]])
bi_model <- libbi(model)
input_lst <- list(N = 52196381)
end_time <- max(y$time)
obs_lst <- list(y = y %>% dplyr::filter(time <= end_time))
init_list <- list(k=3,gamma=3,sigma=sqrt(0.003),tau=0.8)

bi <- sample(bi_model, end_time = end_time, input = input_lst, init=init_list, obs = obs_lst, nsamples = 1000, nparticles = minParticles, nthreads = ncores, proposal = 'model',seed=0123112) %>% 
  adapt_particles(min = minParticles, max = minParticles*500) %>%
  adapt_proposal(min = 0.1, max = 0.4) %>%
  sample(nsamples = 1, thin = 1) %>% # burn in 
  sample(nsamples = 5000, thin = 5)

bi_lst <- bi_read(bi %>% sample_obs)

write.csv(bi_lst,"../data/para1_model8.csv")
fitY <- bi_lst$y %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(y %>% rename(Y = value))
write.csv(fitY,"../data/para1_y8.csv")

plot_df <- bi_lst$x %>% mutate(value = exp(value)) %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup()
write.csv(plot_df,"../data/para1_beta8.csv")

Mmodel <- read.csv("Covidbm11.csv", header=TRUE, stringsAsFactors=FALSE)
S<-Mmodel[,4]
E<-Mmodel[,5]
I<-Mmodel[,6]
R<-Mmodel[,7]

S <- data.frame(value = S) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, value)
fitS <-bi_lst$S %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(S %>% rename(S = value))
write.csv(fitS,"../data/para1_S8.csv")

E <- data.frame(value = E) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, value)
fitE <-bi_lst$E %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(E %>% rename(E = value))
write.csv(fitE,"../data/para1_E8.csv")

I <- data.frame(value = I) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, value)
fitI <-bi_lst$I %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(I %>% rename(I = value))
write.csv(fitI,"../data/para1_I8.csv")

R <- data.frame(value = R) %>%
  mutate(time = seq(1, by = 1, length.out = n())) %>%
  dplyr::select(time, value)
fitR <-bi_lst$R %>%
  group_by(time) %>%
  mutate(
    q025 = quantile(value, 0.025),
    q25 = quantile(value, 0.25),
    q50 = quantile(value, 0.5),
    q75 = quantile(value, 0.75),
    q975 = quantile(value, 0.975)
  ) %>% ungroup() %>%
  left_join(R %>% rename(R = value))
write.csv(fitR,"../data/para1_R8.csv")

write.csv(1/bi_lst$k$value,"../data/para1_alpha8.csv")
write.csv(1/bi_lst$gamma$value,"../data/para1_gamma8.csv")
write.csv(bi_lst$sigma$value,"../data/para1_sigma8.csv")
write.csv(bi_lst$tau$value,"../data/para1_tau8.csv")

```

```{r}
#generate simulations
library(fs)
library(purrr)
library(rlang)
library(whisker)

# Parameter options - edit this bit
param_options <- list(
    initial_z = c(0, 1, 2),
    dxdt = c("sigma*e", "-sigma*e"),
    param_k = c("truncated_gaussian(5, {{ k_dist_stdev }}, lower = 0)"),
    k_dist_stdev = c(0.01, 0.02)
)

# Generate a set of null 'parameter values' which when rendered into the
# template don't actually change it.
null_params <- list()
for (param_name in names(param_options)) {
    null_params[[param_name]] <- paste0("{{ ", param_name, " }}")
}

# Produce parameter combinations
combinations_df <- expand.grid(param_options)

# Read in template scripts
template <- readLines("para_template.R")
data_template <- readLines("data_generation_template.R")

#' Create a file and write content
#'
#' Creates any necessary directories
write_file <- function(file_path, content) {
    dir.create(dirname(file_path), recursive = TRUE)

    file_conn <- file(file_path)
    writeLines(content, file_conn)
    close(file_conn)
}

#' Function to generate a simulation file from template
generate <- function(param_set) {
    # Put parameters into template one by one
    # We need to use the null values here since `whisker.render` expects
    # all parameters to be given in one go.
    output <- template
    data_output <- data_template
    for (param_name in names(param_set)) {
        param_list <- null_params
        param_list[[param_name]] <- param_set[param_name]
        output <- whisker.render(output, param_list)
        data_output <- whisker.render(data_output, param_list)
    }

    path_reduce <- function(path, part) {
        file.path(path, path_sanitize(part))
    }

    # Create output directory
    path <- reduce(param_set, path_reduce, .init = ".")

    # Save output R script
    file_path <- file.path(path, "para.R")
    write_file(file_path, output)

    # Save output data generation R script
    file_path <- file.path(path, "data_generation.R")
    write_file(file_path, data_output)
}

# Apply above function to dataframe of parameter combinations
apply(combinations_df, 1, generate)

print(warnings())

```